language: cpp
dist: xenial

cache:
  directories:
    - $HOME/.ccache
    - $HOME/deps

addons:
  apt:
    update: true
    sources: &default_sources
      - ubuntu-toolchain-r-test
      - boost-latest
    packages: &default_packages
      # - libhdf5-dev
      - doxygen
      - graphviz
      - r-base
      - libxml2-dev

matrix:
  include:

    #- os: linux
    #  compiler: gcc
    #  env: MATRIX_EVAL="CC=gcc-7 && CXX=g++-7 && MAKE_TEST=true"
    #  addons: {apt: { packages: [*default_packages, g++-7], sources: [*default_sources]}}

    #- os: linux
    #  compiler: gcc
    #  env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && TRAVIS_BUILD_DOCS=true"
    #  addons: {apt: { packages: [*default_packages, g++-8], sources: [*default_sources]}}

    #- os: linux
    #  compiler: clang
    #  env: MATRIX_EVAL="CC=clang && CXX=clang++ && MAKE_TEST=true"
    #  addons: {apt: { packages: [*default_packages], sources: [*default_sources]}}

    - os: linux
      compiler: gcc
      language: r
      env: MATRIX_EVAL="CC=gcc-8 && CXX=g++-8 && R_TEST=true"
      addons: {apt: { packages: [*default_packages, g++-8], sources: [*default_sources]}}
      r-packages= devtools XML ggplot2
      cran: http://cran.rstudio.com
      warnings_are_errors: true
      
  
    #- os: osx
    #  osx_image: xcode10.1
    #  compiler: clang
    #  env: MATRIX_EVAL="CXX_ID=clang7 && CC=clang && CXX=clang++ && MAKE_TEST=true"

    #- os: osx
    #  osx_image: xcode10.1
    #  compiler: clang
    #  env: MATRIX_EVAL="CXX_ID=apple && CC=cc && CXX=c++"

before_install:
  - eval "${MATRIX_EVAL}"
  # OpenMP issue with linux+clang
  #- export LD_LIBRARY_PATH=/usr/local/clang/lib:$LD_LIBRARY_PATH
  # Check commit matches expected commit (because of Travis bug)


install:
    #--------- All platforms


script:
  #- make all && if [[ "$MAKE_TEST" = "true" ]]; then make test; fi && if [[ "$R_TEST" = "true" ]]; then make rtest; fi
  - make rtest

after_success:
    # Generate the docs only if master, the travis_build_docs is true and we can use secure variables
  - |
    if [[ "$TRAVIS_BRANCH" = "master" && "$TRAVIS_BUILD_DOCS" = "true" && "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      cd $TRAVIS_BUILD_DIR
      chmod +x resources/sh/generate-doxygen.sh
      resources/sh/generate-doxygen.sh
    fi
